image:
  repository: 957117875403.dkr.ecr.us-east-1.amazonaws.com/devsecops-app
  tag: "1"
  pullPolicy: Always

replicaCount: 1

service:
  port: 5000

env:
  ENVIRONMENT: "dev"
  DB_HOST: "localhost"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_NAME: "testdb"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
imagePullSecrets:
  - name: ecr-secret
livenessProbe: null
readinessProbe: null

